stages: [generate, build]

variables:
  SPACK_REPO: https://github.com/spack/spack.git
  SPACK_REF: v0.16.1

generate-pipeline:
  stage: generate
  before_script:
    - git clone ${SPACK_REPO} --branch ${SPACK_REF}
    - pushd ./spack && git checkout ${SPACK_REF} && popd
    - . "./spack/share/spack/setup-env.sh"
    - spack --version
  script:
    - spack env activate --without-view .
    - spack -d ci generate
      --output-file "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
  after_script:
    - rm -rf "./spack"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
  image: { "name": "spack/ubuntu-bionic", "entrypoint": [""] }
  tags: ["spack", "public", "medium", "x86_64"]

build-jobs:
  stage: build
  trigger:
    include:
      - artifact: "jobs_scratch_dir/pipeline.yml"
        job: generate-pipeline
    strategy: depend
