stages: [generate, build]

generate-pipeline:
  stage: generate
  before_script:
    - git clone ${SPACK_REPO} --branch ${SPACK_REF}
    - pushd ./spack && export CURRENT_SPACK_SHA=$(git rev-parse HEAD) && popd
    - . "./spack/share/spack/setup-env.sh"
  script:
    - spack env activate .
    - spack -d ci generate
      --spack-repo ${SPACK_REPO}
      --spack-ref ${CURRENT_SPACK_SHA}
      --output-file "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
  after_script:
    - rm -rf "./spack"
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/jobs_scratch_dir/pipeline.yml"
  image: { "name": "ecpe4s/centos7-runner:1.0", "entrypoint": [""] }
  tags: ["spack-kube", "medium"]

build-jobs:
  stage: build
  trigger:
    include:
      - artifact: "jobs_scratch_dir/pipeline.yml"
        job: generate-pipeline
    strategy: depend
